name: BiGR
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 2.1.0
  - torchvision
  - pytorch-cuda=12.1
  - pip:
    - timm
    - diffusers
    - accelerate
    - einops
    - scipy
    - opencv-python